Repository Ircam-Partiels/Partiels, pull requests merged in 2025-04, with the labels that each got.

#92 Ensure that new group name is unique
  Source/Document/AnlDocumentDirector.cpp
Labels: bug

#93 Fix and improve the floating window support on Linux, macOS and Windows
  Dependencies/Misc/Source/MiscFloatingWindow.cpp
Labels: bug

#94 Fix selection of an empty track (when plugin initialisation failed)
  Source/Document/AnlDocumentSelection.cpp
  Source/Track/AnlTrackSection.cpp
  Source/Track/AnlTrackThumbnail.cpp
  Source/Track/AnlTrackTools.cpp
  Source/Track/AnlTrackTools.h
Labels: bug

#95 Fix implicit cast of brackets to a boolean
  Source/Track/Result/AnlTrackResultModifier.cpp
Labels: bug

#96 Remove an obsolete image from the manual
  Docs/Images/section-introduction.2-v1.0.7.png
Labels: documentation

#97 Improve Codacy support on GitHub Actions
  .github/workflows/codacy.yml
Labels: github_actions

#98 Fix and update release notes (VAX plug-in added)
  CMakeLists.txt
Labels: documentation

#101 Fix implicit cast warning
  Source/Track/AnlTrackGraphics.cpp
Labels: bug
